openapi: 3.0.1
info:
  description: "This is a sample server Petstore server. For this sample, you can\
    \ use the api key `special-key` to test the authorization filters."
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenAPI Petstore
  version: 1.0.0
servers:
- url: http://petstore.swagger.io/v2
tags:
- description: Everything about your Pets
  name: pet
- description: Access to Petstore orders
  name: store
- description: Operations about user
  name: user
paths:
  /pet:
    post:
      operationId: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
          application/xml:
            schema:
              $ref: "#/components/schemas/Pet"
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "405":
          content: {}
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Add a new pet to the store
      tags:
      - pet tag
      x-codegen-request-body-name: body
    put:
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
          application/xml:
            schema:
              $ref: "#/components/schemas/Pet"
        description: Pet object that needs to be added to the store
        required: true
      responses:
        "400":
          content: {}
          description: Invalid ID supplied
        "404":
          content: {}
          description: Pet not found
        "405":
          content: {}
          description: Validation exception
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Update an existing pet
      tags:
      - pet tag
      x-codegen-request-body-name: body
  /pet/findByStatus:
    get:
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
      - description: Status values that need to be considered for filter
        explode: false
        in: query
        name: status
        required: true
        schema:
          items:
            default: available
            enum:
            - available
            - pending
            - sold
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
          description: successful operation
        "400":
          content: {}
          description: Invalid status value
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Finds Pets by status
      tags:
      - pet tag
      x-spring-paginated: true
  /pet/findByTags:
    get:
      deprecated: true
      description: "Multiple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing."
      operationId: findPetsByTags
      parameters:
      - description: Tags to filter by
        explode: false
        in: query
        name: tags
        required: true
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Pet"
                type: array
          description: successful operation
        "400":
          content: {}
          description: Invalid tag value
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Finds Pets by tags
      tags:
      - pet tag
      x-spring-paginated: true
  /pet/{petId}:
    delete:
      operationId: deletePet
      parameters:
      - explode: false
        in: header
        name: api_key
        required: false
        schema:
          type: string
        style: simple
      - description: Pet id to delete
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "400":
          content: {}
          description: Invalid pet value
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Deletes a pet
      tags:
      - pet tag
    get:
      description: Returns a single pet
      operationId: getPetById
      parameters:
      - description: ID of pet to return
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Pet"
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
          description: successful operation
        "400":
          content: {}
          description: Invalid ID supplied
        "404":
          content: {}
          description: Pet not found
      security:
      - api_key: []
      summary: Find pet by ID
      tags:
      - pet tag
    post:
      operationId: updatePetWithForm
      parameters:
      - description: ID of pet that needs to be updated
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/updatePetWithForm_request"
      responses:
        "405":
          content: {}
          description: Invalid input
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Updates a pet in the store with form data
      tags:
      - pet tag
  /pet/{petId}/uploadImage:
    post:
      operationId: uploadFile
      parameters:
      - description: ID of pet to update
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadFile_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
          description: successful operation
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: uploads an image
      tags:
      - pet tag
  /pet/{petId}/uploadMultipleImage:
    post:
      operationId: uploadMultipleFile
      parameters:
      - description: ID of pet to update
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadMultipleFile_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
          description: successful operation
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: uploads multiple images
      tags:
      - pet tag
  /pet/{petId}/getImage:
    get:
      operationId: getImage
      parameters:
      - description: ID of pet to get image
        explode: false
        in: path
        name: petId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: successful operation
      security:
      - petstore_auth:
        - write:pets
        - read:pets
      summary: Get an image
      tags:
      - pet tag
  /store/inventory:
    get:
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: successful operation
      security:
      - api_key: []
      summary: Returns pet inventories by status
      tags:
      - store tag
  /store/order:
    post:
      operationId: placeOrder
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Order"
        description: order placed for purchasing the pet
        required: true
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: successful operation
        "400":
          content: {}
          description: Invalid Order
      summary: Place an order for a pet
      tags:
      - store tag
      x-codegen-request-body-name: body
  /store/order/{orderId}:
    delete:
      description: For valid response try integer IDs with value < 1000. Anything
        above 1000 or nonintegers will generate API errors
      operationId: deleteOrder
      parameters:
      - description: ID of the order that needs to be deleted
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content: {}
          description: Invalid ID supplied
        "404":
          content: {}
          description: Order not found
      summary: Delete purchase order by ID
      tags:
      - store tag
    get:
      description: For valid response try integer IDs with value <= 5 or > 10. Other
        values will generate exceptions
      operationId: getOrderById
      parameters:
      - description: ID of pet that needs to be fetched
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          maximum: 5
          minimum: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: successful operation
        "400":
          content: {}
          description: Invalid ID supplied
        "404":
          content: {}
          description: Order not found
      summary: Find purchase order by ID
      tags:
      - store tag
  /user:
    post:
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/User"
        description: Created user object
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      summary: Create user
      tags:
      - user tag
      x-codegen-request-body-name: body
  /user/createWithArray:
    post:
      operationId: createUsersWithArrayInput
      requestBody:
        content:
          '*/*':
            schema:
              items:
                $ref: "#/components/schemas/User"
              type: array
        description: List of user object
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      summary: Creates list of users with given input array
      tags:
      - user tag
      x-codegen-request-body-name: body
  /user/createWithList:
    post:
      operationId: createUsersWithListInput
      requestBody:
        content:
          '*/*':
            schema:
              items:
                $ref: "#/components/schemas/User"
              type: array
        description: List of user object
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      summary: Creates list of users with given input array
      tags:
      - user tag
      x-codegen-request-body-name: body
  /user/login:
    get:
      operationId: loginUser
      parameters:
      - description: The user name for login
        explode: true
        in: query
        name: username
        required: true
        schema:
          type: string
        style: form
      - description: The password for login in clear text
        explode: true
        in: query
        name: password
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              explode: false
              schema:
                format: int32
                type: integer
              style: simple
            X-Expires-After:
              description: date in UTC when token expires
              explode: false
              schema:
                format: date-time
                type: string
              style: simple
        "400":
          content: {}
          description: Invalid username/password supplied
      summary: Logs user into the system
      tags:
      - user tag
  /user/logout:
    get:
      operationId: logoutUser
      responses:
        default:
          content: {}
          description: successful operation
      summary: Logs out current logged in user session
      tags:
      - user tag
    options:
      operationId: logoutUserOptions
      responses:
        default:
          content: {}
          description: endpoint configuration response
      summary: logoutUserOptions
      tags:
      - user tag
  /user/{username}:
    delete:
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - description: The name that needs to be deleted
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content: {}
          description: Invalid username supplied
        "404":
          content: {}
          description: User not found
      summary: Delete user
      tags:
      - user tag
    get:
      operationId: getUserByName
      parameters:
      - description: The name that needs to be fetched. Use user1 for testing.
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: successful operation
        "400":
          content: {}
          description: Invalid username supplied
        "404":
          content: {}
          description: User not found
      summary: Get user by user name
      tags:
      - user tag
    put:
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - description: name that need to be deleted
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/User"
        description: Updated user object
        required: true
      responses:
        "400":
          content: {}
          description: Invalid user supplied
        "404":
          content: {}
          description: User not found
      summary: Updated user
      tags:
      - user tag
      x-codegen-request-body-name: body
  /items/{item$Id}/something/{item$SubId}:
    get:
      description: SQ = "; SBS = \; DBS = \\; SD = $some
      parameters:
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: false
        in: path
        name: item$Id
        required: true
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: simple
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: false
        in: path
        name: item$SubId
        required: true
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: simple
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: true
        in: query
        name: filter$Type
        required: false
        schema:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: form
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: true
        in: query
        name: filter$SubType
        required: false
        schema:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: form
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: false
        in: header
        name: X-Custom_Header
        required: false
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: simple
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: false
        in: header
        name: X-Custom_Header_two
        required: false
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: simple
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: true
        in: cookie
        name: session$Token
        required: false
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: form
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: true
        in: cookie
        name: session$TokenTwo
        required: false
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_items__item_Id__something__item_SubId__get_200_response"
          description: SQ = "; SBS = \; DBS = \\; SD = $some
      summary: SQ = "; SBS = \; DBS = \\; SD = $some
  /items:
    post:
      description: SQ = "; SBS = \; DBS = \\; SD = $some
      parameters:
      - description: SQ = "; SBS = \; DBS = \\; SD = $some
        explode: false
        in: header
        name: X-Post_Header
        required: false
        schema:
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        style: simple
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/_items_post_request"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemWithDollarAttributesAndExamples"
          description: SQ = "; SBS = \; DBS = \\; SD = $some
      summary: SQ = "; SBS = \; DBS = \\; SD = $some
components:
  schemas:
    Order:
      description: An order for a pets from the pet store
      example:
        petId: 6
        quantity: 1
        id: 0
        shipDate: 2000-01-23T04:56:07.000+00:00
        complete: false
        status: placed
      properties:
        id:
          format: int64
          type: integer
        petId:
          format: int64
          type: integer
        quantity:
          format: int32
          type: integer
        shipDate:
          format: date-time
          type: string
        status:
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
          type: string
        complete:
          default: false
          type: boolean
      title: Pet Order
      type: object
      xml:
        name: Order
    Category:
      description: A category for a pet
      example:
        name: name
        id: 6
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      title: Pet category
      type: object
      xml:
        name: Category
    User:
      description: A User who is purchasing from the pet store
      example:
        firstName: firstName
        lastName: lastName
        password: password
        userStatus: 6
        phone: phone
        id: 0
        email: email
        username: username
      properties:
        id:
          format: int64
          type: integer
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          description: User Status
          format: int32
          type: integer
      title: a User
      type: object
      xml:
        name: User
    Tag:
      description: A tag for a pet
      example:
        name: name
        id: 1
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      title: Pet Tag
      type: object
      xml:
        name: Tag
    Pet:
      description: A pet for sale in the pet store
      example:
        photoUrls:
        - photoUrls
        - photoUrls
        name: doggie
        id: 0
        category:
          name: name
          id: 6
        tags:
        - name: name
          id: 1
        - name: name
          id: 1
        status: available
      properties:
        id:
          format: int64
          type: integer
        category:
          $ref: "#/components/schemas/Category"
        name:
          example: doggie
          type: string
        photoUrls:
          items:
            type: string
          type: array
          xml:
            name: photoUrl
            wrapped: true
        tags:
          items:
            $ref: "#/components/schemas/Tag"
          type: array
          xml:
            name: tag
            wrapped: true
        status:
          description: pet status in the store
          enum:
          - available
          - pending
          - sold
          type: string
      required:
      - name
      - photoUrls
      title: a Pet
      type: object
      xml:
        name: Pet
    ApiResponse:
      description: Describes the result of uploading an image resource
      example:
        code: 0
        type: type
        message: message
      properties:
        code:
          format: int32
          type: integer
        type:
          type: string
        message:
          type: string
      title: An uploaded response
      type: object
    ItemWithDollarAttributesAndExamples:
      description: SQ = "; SBS = \; DBS = \\; SD = $some
      example:
        $name: SQ = "; SBS = \; DBS = \\; SD = $some
        $id: SQ = "; SBS = \; DBS = \\; SD = $some
      properties:
        $id:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        $name:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
      type: object
    updatePetWithForm_request:
      properties:
        name:
          description: Updated name of the pet
          type: string
        status:
          description: Updated status of the pet
          type: string
    uploadFile_request:
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        image:
          description: image to upload
          format: binary
          type: string
      required:
      - image
    uploadMultipleFile_request:
      properties:
        additionalMetadata:
          description: Additional data to pass to server
          type: string
        images:
          items:
            description: image to upload
            format: binary
            type: string
          type: array
      required:
      - images
    _items__item_Id__something__item_SubId__get_200_response_details_Info:
      description: SQ = "; SBS = \; DBS = \\; SD = $some
      example:
        detail$One: SQ = "; SBS = \; DBS = \\; SD = $some
        detail$Two: 42
      properties:
        detail$One:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        detail$Two:
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: 42
          type: integer
      type: object
    _items__item_Id__something__item_SubId__get_200_response:
      example:
        name$Value: SQ = "; SBS = \; DBS = \\; SD = $some
        details$Info:
          detail$One: SQ = "; SBS = \; DBS = \\; SD = $some
          detail$Two: 42
        item$Id: SQ = "; SBS = \; DBS = \\; SD = $some
      properties:
        item$Id:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        name$Value:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        details$Info:
          $ref: "#/components/schemas/_items__item_Id__something__item_SubId__get_200_response_details_Info"
      type: object
    _items_post_request:
      properties:
        form$Name:
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
        form$Value:
          default: SQ = "; SBS = \; DBS = \\; SD = $some
          description: SQ = "; SBS = \; DBS = \\; SD = $some
          example: SQ = "; SBS = \; DBS = \\; SD = $some
          type: string
      type: object
  securitySchemes:
    petstore_auth:
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
      type: oauth2
    api_key:
      in: header
      name: api_key
      type: apiKey
